package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"go-template/daos"
	"go-template/gqlmodels"
	"go-template/pkg/utl/cnvrttogql"
)

// GetPosts is the resolver for the getPosts field.
func (r *queryResolver) GetPosts(ctx context.Context) (*gqlmodels.PostPayload, error) {
	posts, err := daos.FetchAllPosts(ctx)
	if err != nil {
		return nil, err
	}

	gqlPosts := cnvrttogql.PostsToGraphQlPosts(posts)
	return &gqlmodels.PostPayload{
		Posts: gqlPosts,
	}, nil
}
