// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testRolesTests(t *testing.T) {
	t.Parallel()

	query := RolesTests()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testRolesTestsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RolesTest{}
	if err = randomize.Struct(seed, o, rolesTestDBTypes, true, rolesTestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RolesTest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RolesTests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRolesTestsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RolesTest{}
	if err = randomize.Struct(seed, o, rolesTestDBTypes, true, rolesTestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RolesTest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := RolesTests().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RolesTests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRolesTestsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RolesTest{}
	if err = randomize.Struct(seed, o, rolesTestDBTypes, true, rolesTestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RolesTest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RolesTestSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := RolesTests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRolesTestsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RolesTest{}
	if err = randomize.Struct(seed, o, rolesTestDBTypes, true, rolesTestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RolesTest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := RolesTestExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if RolesTest exists: %s", err)
	}
	if !e {
		t.Errorf("Expected RolesTestExists to return true, but got false.")
	}
}

func testRolesTestsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RolesTest{}
	if err = randomize.Struct(seed, o, rolesTestDBTypes, true, rolesTestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RolesTest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	rolesTestFound, err := FindRolesTest(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if rolesTestFound == nil {
		t.Error("want a record, got nil")
	}
}

func testRolesTestsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RolesTest{}
	if err = randomize.Struct(seed, o, rolesTestDBTypes, true, rolesTestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RolesTest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = RolesTests().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testRolesTestsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RolesTest{}
	if err = randomize.Struct(seed, o, rolesTestDBTypes, true, rolesTestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RolesTest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := RolesTests().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testRolesTestsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	rolesTestOne := &RolesTest{}
	rolesTestTwo := &RolesTest{}
	if err = randomize.Struct(seed, rolesTestOne, rolesTestDBTypes, false, rolesTestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RolesTest struct: %s", err)
	}
	if err = randomize.Struct(seed, rolesTestTwo, rolesTestDBTypes, false, rolesTestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RolesTest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = rolesTestOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = rolesTestTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := RolesTests().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testRolesTestsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	rolesTestOne := &RolesTest{}
	rolesTestTwo := &RolesTest{}
	if err = randomize.Struct(seed, rolesTestOne, rolesTestDBTypes, false, rolesTestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RolesTest struct: %s", err)
	}
	if err = randomize.Struct(seed, rolesTestTwo, rolesTestDBTypes, false, rolesTestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RolesTest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = rolesTestOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = rolesTestTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RolesTests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testRolesTestsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RolesTest{}
	if err = randomize.Struct(seed, o, rolesTestDBTypes, true, rolesTestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RolesTest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RolesTests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRolesTestsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RolesTest{}
	if err = randomize.Struct(seed, o, rolesTestDBTypes, true); err != nil {
		t.Errorf("Unable to randomize RolesTest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(rolesTestColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := RolesTests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRolesTestsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RolesTest{}
	if err = randomize.Struct(seed, o, rolesTestDBTypes, true, rolesTestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RolesTest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRolesTestsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RolesTest{}
	if err = randomize.Struct(seed, o, rolesTestDBTypes, true, rolesTestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RolesTest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RolesTestSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRolesTestsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &RolesTest{}
	if err = randomize.Struct(seed, o, rolesTestDBTypes, true, rolesTestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RolesTest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := RolesTests().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	rolesTestDBTypes = map[string]string{`ID`: `int`, `AccessLevel`: `int`, `Name`: `text`, `CreatedAt`: `timestamp`, `UpdatedAt`: `timestamp`, `DeletedAt`: `timestamp`}
	_                = bytes.MinRead
)

func testRolesTestsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(rolesTestPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(rolesTestAllColumns) == len(rolesTestPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &RolesTest{}
	if err = randomize.Struct(seed, o, rolesTestDBTypes, true, rolesTestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RolesTest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RolesTests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, rolesTestDBTypes, true, rolesTestPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RolesTest struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testRolesTestsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(rolesTestAllColumns) == len(rolesTestPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &RolesTest{}
	if err = randomize.Struct(seed, o, rolesTestDBTypes, true, rolesTestColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize RolesTest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := RolesTests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, rolesTestDBTypes, true, rolesTestPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RolesTest struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(rolesTestAllColumns, rolesTestPrimaryKeyColumns) {
		fields = rolesTestAllColumns
	} else {
		fields = strmangle.SetComplement(
			rolesTestAllColumns,
			rolesTestPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := RolesTestSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testRolesTestsUpsert(t *testing.T) {
	t.Parallel()

	if len(rolesTestAllColumns) == len(rolesTestPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLRolesTestUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := RolesTest{}
	if err = randomize.Struct(seed, &o, rolesTestDBTypes, false); err != nil {
		t.Errorf("Unable to randomize RolesTest struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert RolesTest: %s", err)
	}

	count, err := RolesTests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, rolesTestDBTypes, false, rolesTestPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize RolesTest struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert RolesTest: %s", err)
	}

	count, err = RolesTests().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
